FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b AS certs
RUN apk --update add ca-certificates

# FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b AS collector-build
# COPY ./collector/dist/otel-shopping-cart-collector /otel-shopping-cart-collector
# RUN chmod 755 /otel-shopping-cart-collector

FROM ubuntu:22.04@sha256:77906da86b60585ce12215807090eb327e7386c8fafb5402369e421f44eff17e AS collector-build

RUN apt-get update
RUN apt-get install -y wget git gcc curl

RUN wget -P /tmp "https://dl.google.com/go/go1.22.4.linux-amd64.tar.gz"

RUN tar -C /usr/local -xzf "/tmp/go1.22.4.linux-amd64.tar.gz"
RUN rm "/tmp/go1.22.4.linux-amd64.tar.gz"

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

RUN curl --proto '=https' --tlsv1.2 -fL -o ocb https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.102.1/ocb_0.102.1_linux_amd64
RUN chmod +x ocb

COPY ./collector/manifest.yaml ./collector/manifest.yaml
RUN CGO_ENABLED=0 ./ocb --config ./collector/manifest.yaml --skip-strict-versioning
RUN cp -r ./collector/dist/otel-shopping-cart-collector /otel-shopping-cart-collector
LABEL org.opencontainers.image.source https://github.com/trstringer/manual-approval

ARG USER_UID=10001
USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/otel-shopping-cart-collector"]
EXPOSE 4317 55678 55679
