grafana:
  image: 
    repository: grafana/grafana
    tag: 11.0.0
  extraVolumeMounts:
    - name: grafana-storage
      mountPath: /var/lib/grafana/plugins
  extraVolumes:
    - name: grafana-storage
      emptyDir: {}
  extraInitContainers:
    - name: install-plugins
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /var/lib/grafana/plugins/grafana-lokiexplore-app;
          wget -qO /tmp/grafana-lokiexplore-app-latest.zip https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;
          unzip /tmp/grafana-lokiexplore-app-latest.zip -d /var/lib/grafana/plugins/grafana-lokiexplore-app;
          rm -f /tmp/grafana-lokiexplore-app-latest.zip;
      volumeMounts:
        - name: grafana-storage
          mountPath: "/var/lib/grafana/plugins"
  grafana.ini:
    auth:
      disable_login_form: true
      disable_signout_menu: true
    users:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
  additionalDataSources:
    - name: Tempo
      url: http://tempo:3100
      access: proxy
      basicAuth: false
      type: tempo
      orgId: 1
      version: 1
      uid: tempo
      editable: false
      apiVersion: 1
    - name: Loki
      url: http://loki:3100
      access: proxy
      basicAuth: false
      type: loki
      orgId: 1
      version: 1
      uid: loki
      editable: false
      apiVersion: 1
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '1'

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: otel
    podMonitorSelector:
      matchLabels:
        release: otel
